import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";


const GK_Dinkum_Regular = localFont({
  src: "../../assets/fonts/GE Dinkum Regular.ttf",
  variable: "--font-gk-dinkum-regular",
});

const GK_Dinkum_Bold = localFont({
  src: "../../assets/fonts/GE Dinkum Bold.ttf",
  variable: "--font-gk-dinkum-bold",
});


export const metadata: Metadata = {
  title: "قرض حسن",
  description: "Generated by create next app",
};

// const messagesMap: Record<string, () => Promise<Record<string, unknown>>> = {
//   en: () => import('../../../messages/en.json').then(m => m.default as Record<string, unknown>),
//   ar: () => import('../../../messages/ar.json').then(m => m.default as Record<string, unknown>),
// };


export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {



  const { locale } = await params;
  // const messages = await messagesMap[locale]();
  const dir = locale === "ar" ? "rtl" : "ltr";

  const fontClass = locale === "ar" ? `${GK_Dinkum_Regular.variable} ${GK_Dinkum_Bold.variable} font-gk-dinkum-regular` : "font-sans";

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${fontClass} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
