import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { UserProvider } from '@/contexts/UserContext';
import { NotificationProvider } from '@/contexts/NotificationContext';
import { ToastProvider } from '@/components/providers/toast-provider';


const GK_Dinkum_Regular = localFont({
  src: "../../assets/fonts/GE Dinkum Regular.ttf",
  variable: "--font-gk-dinkum-regular",
});

const GK_Dinkum_Bold = localFont({
  src: "../../assets/fonts/GE Dinkum Bold.ttf",
  variable: "--font-gk-dinkum-bold",
});


export const metadata: Metadata = {
  title: "قرض حسن",
  description: "Generated by create next app",
};




export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {

  const { locale } = await params;
  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  const fontClass = locale === "ar" ? `${GK_Dinkum_Regular.variable} ${GK_Dinkum_Bold.variable} font-gk-dinkum-regular` : "font-sans";

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${fontClass} antialiased`}
        suppressHydrationWarning={true}
      >
        <NextIntlClientProvider messages={messages}>
          <UserProvider>
            <NotificationProvider>
              <ToastProvider />
              {children}
            </NotificationProvider>
          </UserProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
