import type { Metadata } from "next";
import "@/app/globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { UserProvider } from '@/contexts/UserContext';
import { ToastProvider } from '@/components/providers/toast-provider';


export const metadata: Metadata = {
  title: "قرض حسن",
  description: "Generated by create next app",
};




export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {

  const { locale } = await params;
  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  const fontClass = locale === "ar" ? "font-gk-dinkum-regular" : "font-sans";

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${fontClass} antialiased`}
        suppressHydrationWarning={true}
      >
        <NextIntlClientProvider messages={messages}>
          <UserProvider>
            <ToastProvider />
            {children}
          </UserProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
